# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe3790ac9040576c299ab856385f61cc0b03c125072b8512d208d2571f6a3df84fd7b8ec09c83f8244324ab2b5b8fdf95cee1e93955d29b45587464aa5894cf7

test:
  secret_key_base: 9a5631516c5b13d45f0b8c4b42c8b2817ab9bcb786fe095a319afc0c91ea010067560a6d793bad9f42b4b78bc28826964a21e3aa42d8753e719e67f430342324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
